# Generated by Django 2.2.3 on 2020-12-13 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profilepic'),
            preserve_default=False,
        ),
    ]
