# Generated by Django 2.2.3 on 2020-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilefor',
            field=models.CharField(default='Self', max_length=50),
        ),
    ]
