# Generated by Django 2.2.3 on 2020-12-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_auto_20201213_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Work',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
