# Generated by Django 2.2.3 on 2020-12-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_user_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Work',
            new_name='work',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
